services:

  api_debug:
    build:
      context: .
      dockerfile: debug.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - PORT=3000
      - BUCKET=hello-catalog
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-west-2

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - api_debug

  proxy:
    image: nginx:1.26-bookworm
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api_debug
