services:

  api_debug:
    build:
      context: .
      dockerfile: debug.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - PORT=3000
      - BUCKET=hello-catalog
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-west-2
      
  api_release:
    build:
      context: .
      dockerfile: release.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - PORT=3000
      - BUCKET=hello-catalog
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=us-west-2

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api_debug
